# -*- coding: utf-8 -*-
"""Analysis:datascience.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sijAuL7_-b_1egGF2ugTX7mQsJeO2T6F

### Importação dos dados
"""

import pandas as pd

url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja= pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja4.head()

"""#1. Análise do faturamento

"""

todas_lojas = pd.concat([loja, loja2, loja3, loja4], ignore_index=True)

# Calculando o total da compra (preço + frete)
todas_lojas["total_compra"] = todas_lojas["Preço"] + todas_lojas["Frete"]

print("Faturamento por loja:")
for i, loja in enumerate([loja, loja2, loja3, loja4], start=1):
    faturamento = loja["Preço"].sum() + loja["Frete"].sum()
    print(f"Loja {i}: R$ {faturamento:.2f}")

# Exibindo o total geral faturado
faturamento_total = todas_lojas["total_compra"].sum()
print(f"\nFaturamento total (todas as lojas): R$ {faturamento_total:.2f}")

# Exibindo as primeiras linhas do DataFrame final
print("\nExemplo de dados consolidados:")
print(todas_lojas.head())

"""# 2. Vendas por Categoria

"""

# Agrupando por categoria e somando as vendas
vendas_categoria = todas_lojas.groupby("Categoria do Produto")["total_compra"].sum().sort_values(ascending=False)

# Exibindo o resultado
print("Vendas por Categoria (Total de Faturamento):\n")
print(vendas_categoria)

"""# 3. Média de Avaliação das Lojas"""

loja["Loja"] = "Loja 1"
loja2["Loja"] = "Loja 2"
loja3["Loja"] = "Loja 3"
loja4["Loja"] = "Loja 4"
todas_lojas = pd.concat([loja, loja2, loja3, loja4], ignore_index=True)
media_avaliacao = todas_lojas.groupby("Loja")["Avaliação da compra"].mean().round(2)

print("Média de Avaliação das Lojas:\n")
print(media_avaliacao)

"""# 4. Produtos Mais e Menos Vendidos"""

vendas_produto = todas_lojas["Produto"].value_counts()
# Produto mais vendido
mais_vendido = vendas_produto.idxmax()
qtd_mais_vendido = vendas_produto.max()

# Produto menos vendido
menos_vendido = vendas_produto.idxmin()
qtd_menos_vendido = vendas_produto.min()

print("Produto mais vendido:")
print(f"{mais_vendido} - {qtd_mais_vendido} vendas\n")

print("Produto menos vendido:")
print(f"{menos_vendido} - {qtd_menos_vendido} venda(s)\n")

"""# 5. Frete Médio por Loja

"""

frete_medio = todas_lojas.groupby("Loja")["Frete"].mean().round(2)

print("Frete Médio por Loja:\n")
print(frete_medio)